services:
  - type: web
    name: roblox-presence-bot
    env: node
    buildCommand: npm install
    startCommand: node --dns-result-order=ipv4first src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: ROBLOX_CLIENT_ID
        sync: false
      - key: ROBLOX_CLIENT_SECRET
        sync: false
      - key: ROBLOX_REDIRECT_URI
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
